# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 785)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_link_label = QtWidgets.QLabel(self.centralwidget)
        self.input_link_label.setGeometry(QtCore.QRect(20, 20, 111, 21))
        self.input_link_label.setObjectName("input_link_label")
        self.videotitle = QtWidgets.QLabel(self.centralwidget)
        self.videotitle.setGeometry(QtCore.QRect(20, 270, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.videotitle.setFont(font)
        self.videotitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.videotitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.videotitle.setWordWrap(True)
        self.videotitle.setObjectName("videotitle")
        self.thumb = QtWidgets.QGraphicsView(self.centralwidget)
        self.thumb.setGeometry(QtCore.QRect(20, 80, 320, 180))
        self.thumb.setObjectName("thumb")
        self.input_link_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.input_link_label_2.setGeometry(QtCore.QRect(370, 320, 301, 21))
        self.input_link_label_2.setObjectName("input_link_label_2")
        self.new_desc = QtWidgets.QTextEdit(self.centralwidget)
        self.new_desc.setGeometry(QtCore.QRect(370, 340, 301, 111))
        self.new_desc.setObjectName("new_desc")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(690, 370, 111, 51))
        self.update_btn.setObjectName("update_btn")
        self.input_link_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.input_link_label_3.setGeometry(QtCore.QRect(370, 260, 301, 21))
        self.input_link_label_3.setObjectName("input_link_label_3")
        self.new_title = QtWidgets.QTextEdit(self.centralwidget)
        self.new_title.setGeometry(QtCore.QRect(370, 280, 301, 31))
        self.new_title.setPlaceholderText("")
        self.new_title.setObjectName("new_title")
        self.update_title_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_title_btn.setGeometry(QtCore.QRect(690, 280, 111, 31))
        self.update_title_btn.setObjectName("update_title_btn")
        self.link_input_box = QtWidgets.QLineEdit(self.centralwidget)
        self.link_input_box.setGeometry(QtCore.QRect(20, 40, 321, 20))
        self.link_input_box.setObjectName("link_input_box")
        self.read_video_desc = QtWidgets.QTextBrowser(self.centralwidget)
        self.read_video_desc.setGeometry(QtCore.QRect(20, 340, 321, 111))
        self.read_video_desc.setObjectName("read_video_desc")
        self.send_chatgpt_somthing = QtWidgets.QLabel(self.centralwidget)
        self.send_chatgpt_somthing.setGeometry(QtCore.QRect(370, 20, 301, 21))
        self.send_chatgpt_somthing.setObjectName("send_chatgpt_somthing")
        self.ask_chatgpt = QtWidgets.QTextEdit(self.centralwidget)
        self.ask_chatgpt.setGeometry(QtCore.QRect(370, 40, 301, 31))
        self.ask_chatgpt.setObjectName("ask_chatgpt")
        self.gpt_response = QtWidgets.QTextBrowser(self.centralwidget)
        self.gpt_response.setGeometry(QtCore.QRect(370, 80, 301, 181))
        self.gpt_response.setObjectName("gpt_response")
        self.ask_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ask_btn.setGeometry(QtCore.QRect(690, 40, 111, 31))
        self.ask_btn.setObjectName("ask_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_link_label.setText(_translate("MainWindow", "Input Link"))
        self.videotitle.setText(_translate("MainWindow", "Title"))
        self.input_link_label_2.setText(_translate("MainWindow", "New Description"))
        self.update_btn.setText(_translate("MainWindow", "Update Description"))
        self.input_link_label_3.setText(_translate("MainWindow", "New Title"))
        self.update_title_btn.setText(_translate("MainWindow", "Update Title"))
        self.link_input_box.setPlaceholderText(_translate("MainWindow", "https://youtube.com/...."))
        self.read_video_desc.setPlaceholderText(_translate("MainWindow", "Description"))
        self.send_chatgpt_somthing.setText(_translate("MainWindow", "Ask Chat GPT for a better Title and Description"))
        self.ask_chatgpt.setPlaceholderText(_translate("MainWindow", "Could you write a title for a video that is about the IPhone."))
        self.gpt_response.setPlaceholderText(_translate("MainWindow", "response"))
        self.ask_btn.setText(_translate("MainWindow", "Ask..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
